MODULE grid_data
   IMPLICIT NONE
   INTEGER :: MPTS = 2000  ! Now a variable, not parameter
   REAL, ALLOCATABLE :: GRD(:)
END MODULE grid_data

MODULE molecular_data
   IMPLICIT NONE
   INTEGER, PARAMETER :: MCENT = 200
   INTEGER, PARAMETER :: MMO = 500
   DOUBLE PRECISION :: XC(MCENT), YC(MCENT), ZC(MCENT), CHARG(MCENT)
   DOUBLE PRECISION :: EORB(MMO), PO(MMO)
   INTEGER :: NCENT, NMO
END MODULE molecular_data

MODULE basis_data
   IMPLICIT NONE
   INTEGER, PARAMETER :: MPRIMS = 2000
   INTEGER, PARAMETER :: NTYPE = 20
   DOUBLE PRECISION :: DIV(MPRIMS), COO(MPRIMS,500), EXX(MPRIMS), SUM(MPRIMS)
   INTEGER :: ICT(MPRIMS), ITP(NTYPE), NPRIMS
END MODULE basis_data

MODULE string_data
   IMPLICIT NONE
   CHARACTER*80 :: WFNTTL, JOBTTL
   CHARACTER*8 :: ATNAM(200)
   INTEGER :: NAT
END MODULE string_data

MODULE io_units
   IMPLICIT NONE
   INTEGER :: INPT, IOUT, IWFN, IDBG
END MODULE io_units

MODULE computation_data
   IMPLICIT NONE
   DOUBLE PRECISION :: THRESH1, THRESH2, GAMMA, TOTE
END MODULE computation_data

MODULE work_arrays
   IMPLICIT NONE
   INTEGER, PARAMETER :: MPTS_WORK = 2000
   INTEGER, PARAMETER :: MMO_WORK = 500
   DOUBLE PRECISION :: PSI(MPTS_WORK,MMO_WORK), GX(MPTS_WORK,MMO_WORK)
   DOUBLE PRECISION :: GY(MPTS_WORK,MMO_WORK), GZ(MPTS_WORK,MMO_WORK)
   DOUBLE PRECISION :: D2(MPTS_WORK,MMO_WORK)
END MODULE work_arrays