! Generated from gridv.f
! Main program

      PROGRAM GRIDV                                                  
C
C     VERSION 94 Revision A
C
C     GRIDV CUTS A PLANE FROM THREE SPACE AND CALCULATES
C     THE DESIRED FUNCTION AT POINTS ON A GRID OVERLAID UPON
C     THE PLANE.  THE POSSIBLE FUNCTIONS ARE:
C     1   RHO
C     2   DEL**2(RHO)
C     3   KE (G)
C
C     OTHERS ARE EASILY ADDED ...
C
C     GRIDV IS A MODIFIED VERSION OF GRID.
C
C     GRID TO GRIDV BY T.A. KEITH, 1991
C
C     GRIDV CAN HANDLE S,P,D(6) AND F(10) GAUSSIAN FUNCTIONS
C     MODIFIED TO INCLUDE F-FUNCTIONS BY RICHARD G. A. BONE, 1993
C
C     Cleaned Up Jan. 1994.  TAK
C
C     QUESTIONS AND SUGGESTIONS SHOULD BE DIRECTED TO:
C     T.A. KEITH:  keith@babbage.chemistry.mcmaster.ca
C     or
C     R.F.W. Bader:  bader@mcmail.cis.mcmaster.ca
C
C     TO REDIMENSION GRIDV TO HANDLE MORE MO's, PRIMITIVES AND NUCLEI
C     CHANGE THE VALUES MMO, MPRIMS AND MCENT IN THE PARAMETER
C     STATEMENTS.  TO CHANGE THE MAXIMUM GRID SIZE, CHANGE THE PARAMETER
C     MPts.
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)                               
      REAL GRD
      CHARACTER*80 WFNTTL,LINE,JOBTTL
      CHARACTER*8 ATNAM,WORD
      CHARACTER*40 WINP,WOUT,WFN,WDBG
      CHARACTER*4 FINP /'.inf'/, FOUT /'.grd'/, FWFN /'.wfn'/
      PARAMETER(MCENT=200,MMO=500,MPRIMS=2000,MPTS=2000)
      DIMENSION A(3,3),IR(MCENT),CX(3),E(3),CT(3)
      DIMENSION XS(3,MCENT),X(3,MCENT),XY(4)                          
      COMMON /GRID/ GRD(MPTS*MPTS)
      COMMON /ATOMS/ XC(MCENT),YC(MCENT),ZC(MCENT),CHARG(MCENT),NCENT
      COMMON /ORBTL/ EORB(MMO),PO(MMO),NMO
      COMMON /STRING/ WFNTTL,JOBTTL,ATNAM(MCENT),NAT
      COMMON /UNITS/ INPT,IOUT,IWFN,IDBG
      COMMON /VALUES/ THRESH1,THRESH2,GAMMA,TOTE
      DATA LEVEL/1/,NAE/99/,ISRF/2/,INPT/20/,IOUT/30/,IWFN/10/
C
      CALL MAKNAME(1,WINP,ILEN,FINP)
      IF (ILEN .EQ. 0) STOP 'usage: gridv inffile wfnfile '
      CALL MAKNAME(2,WFN,ILEN,FWFN)
      IF (ILEN .EQ. 0) STOP 'usage: gridv inffile wfnfile '
C     Generate output filename from input filename
      CALL GETARG(1,WOUT)
      CALL MAKNAME_DIRECT(WOUT,ILEN,FOUT)
C     CALL MAKNAME(1,WDBG,ILEN,FDBG)
C
      OPEN (INPT,FILE=WINP)
      OPEN (IOUT,FILE=WOUT,FORM='FORMATTED')
      OPEN (IWFN,FILE=WFN)
C     OPEN (IDBG,FILE=WDBG)
C
C    READ WAVEFUNCTION FILE
C
      CALL RDPSI
C
C    INPUT PARAMETERS FOR GRIDV
C
C    READS ARE DONE USING THE FUNCTION CALL NUMBER UPON THE
C    INPUT STRING.  LPST IS THE POSITION FROM WHICH THE READ
C    IS DONE.  ITS VALUE IS UPDATED ONCE THE STRING IS FOUND.
C    THE NUMBER IF RETURNED BOTH AS AN INTEGER (INUM) AND
C    REAL*8 (DNUM).  ONE NEED MERELY REPLACE INUM OR DNUM WITH
C    THE VARIABLE DESIRED TO BE READ.  THE FUNCTION RETURNS A
C    VALUE OF ZERO IF SUCCESSFUL FINDING THE STRING OF INTEREST
C    AND A VALUE OF ONE IF AN ERROR CONDITION OCCURED.
C
C             NUMBER(STRING,LPST,INUM,DNUM)
C
C     UNFORMATTED READ CODE IS DUE TO DR. SIMON K KEARSLEY
C
      READ(INPT,1600) TITLE                                               
C
C    PLOT:   INPUT GRID EDGE SIZE (IN AU) AND INCREMENT.  THIS
C    EFFECTIVELY DESCIBES THE COARSENESS OF THE GRID.  THE
C    SAMPLING IS DONE AT (XY(1)/XY(2))**2) POINTS WITHIN
C    THE PLANE
C
      READ (20,200) LINE                                                
      LPST = 8                                                          
      DO 100 I = 1,2                                                    
      IF (NUMBER(LINE,LPST,NUM,XY(I)) .GT. 0) GOTO 990                  
100   CONTINUE                                                          
C
      IF ( IDINT(XY(1)/XY(2)) .GT. MPTS) THEN
       WRITE (IOUT,101) "The maximum number of points on each side"//
     1  " of the grid is ", MPTS
  101  FORMAT(A55,I5)
       GOTO 1010
      ENDIF
C
      READ (20,200) LINE                                                
      LPST = 8                                                          
      DO 110 I = 1,3                                                    
      IF (NUMBER(LINE,LPST,NUM,CX(I)) .GT. 0) GOTO 992                  
110   CONTINUE                                                          
C
C    PLAN:  DEFINE PLANE THAT IS DESIRED
C    THE REQUIRED ROTATION MATRIX IS GENERATED BY FINDING THE
C    INERTIAL AXIS OF THE ATOMS INPUT IN IR.  TO DEFINE THE PLANE
C    OF INTEREST, ONE NEED ONLY INCLUDE THOSE ATOMS THAT DEFINE
C    THE PLANE.  IF THE PLANE IS DEFINED BY MORE THAN THREE
C    ATOMS,  IT IS BEST TO USE DUMMY ATOM INPUT.  DUMMY ATOMS
C    CAN BE EITHER UNIT VECTORS ALONG COORDINATE AXIS OR
C    COORDINATE POSITIONS IN SPACE.  TO INPUT A DUMMY ATOM,
C    INPUT A NEGATIVE INTEGER INTO IR.  THE ABSOLUTE VALUE OF
C    THE INTEGER WILL CORRESPOND TO WHICH OF THE FOLLOWING DUMMY
C    LINES CORRESPONDS TO THE DESCRIBED ATOM.  FOR EXAMPLE
C    ONE MAY INPUT THE FOLLOWING:
C  PLANE:  1  2 -1
C  DUMMY:  1.0 0.0 0.0
C    THIS WILL PLACE THE XZ PLANE 
 
C    MORE THAN THREE ATOMS OR DUMMY ATOMS CAN BE INPUT IF
C    DESIRED, BUT IT IS RARELY NECESSARY...
C    CODE FOR GENERATION OF INERTIAL AXIS IS DUE TO DR. SIMON K
C    KEARSLEY
C
      READ (20,200) LINE                                                
      LPST = 8                                                          
      IF (NUMBER(LINE,LPST,IEG,DNUM) .GT. 0) GOTO 1100
      IF (IEG .EQ. 0) THEN
      L = 1                                                             
120   IF (NUMBER(LINE,LPST,IR(L),DNUM) .GT. 0) GOTO 10                  
      L = L + 1                                                         
      GOTO 120                                                          
C
C    DECIDE IF DUMMY ATOMS WERE USED AND THEN READ IN THEIR
C    COORDINATES TO XS(3,N)
C
10    DO 130 I = 1,L                                                    
      IF (IR(I) .LT. 0) THEN                                            
      LPST = 8                                                          
      READ (20,200) LINE                                                
      DO 140 K = 1,3                                                    
      IF (NUMBER(LINE,LPST,NUM,XS(K,ABS(IR(I)))) .GT. 0) GOTO 996       
140   CONTINUE                                                          
      END IF                                                            
130   CONTINUE                                                          
C
C    GENERATE REQUIRED ROTATION MATRIX
C
      DO 160 J = 1,NCENT
        X(1,J) = XC(J)
        X(2,J) = YC(J)
        X(3,J) = ZC(J)
160   CONTINUE                                                          
C
      NPLAN = NCENT
      IF (NCENT.EQ.2) NPLAN=3
      CALL GROCKLE(NPLAN,X,IR,XS,A)
C
      ELSE IF (IEG .EQ. 1) THEN
C
      DO 165 J = 1,3
        IF (NUMBER(LINE,LPST,NUM,E(J)) .GT. 0) GOTO 1110
165   CONTINUE
C
      CALL EULER (E,A)
C
      END IF
C
C    READ IN DESIRED FUNCTION 
C
      LPST = 8
      READ (20,200) LINE
      IF (NUMBER(LINE,LPST,IFUNC,DNUM) .GT. 0) GOTO 998
C
C
C    CALL ROUTINE TO CALCULATE DESIRED FUNCTION
C
      IF(IFUNC .EQ. 1) 
     +   CALL GRDRHO (A,CX,XY)
C
      IF(IFUNC .EQ. 2)
     +   CALL GRDD2R (A,CX,XY)
C
      IF(IFUNC .EQ. 3)
     +   CALL GRDKEG (A,CX,XY)
C
C    OUTPUT GRID INFORMATION TO UNIT 30.
C
      NX = IDINT(XY(1)/XY(2))
      CT(1) = A(1,1)*CX(1) + A(2,1)*CX(2) + A(3,1)*CX(3)
      CT(2) = A(1,2)*CX(1) + A(2,2)*CX(2) + A(3,2)*CX(3)
      CT(3) = A(1,3)*CX(1) + A(2,3)*CX(2) + A(3,3)*CX(3)
C
      WRITE (IOUT,'(A)') TRIM(WFNTTL)
      WRITE (IOUT,'(A)') ' '
      WRITE (IOUT,*) NX,NX,XY(1),XY(2)
      WRITE (IOUT,*) IFUNC,NCENT
      WRITE (IOUT,*) (CT(I),I=1,3)
      DO 180 J = 1,NCENT
        XX = A(1,1)*XC(J)+A(2,1)*YC(J)+A(3,1)*ZC(J)-CT(1)
        YY = A(1,2)*XC(J)+A(2,2)*YC(J)+A(3,2)*ZC(J)-CT(2)
        ZZ = A(1,3)*XC(J)+A(2,3)*YC(J)+A(3,3)*ZC(J)-CT(3)
        WRITE (IOUT,*) XX,YY,ZZ
180   CONTINUE
C
      DO 190 J = 1,NX                                                   
      INDX = (J-1)*NX
      WRITE (IOUT,*) (GRD(INDX+I),I=1,NX)                                  
190   CONTINUE                                                          
C
      STOP                                                              
C
C  INPUT ERROR CODES
980   FORMAT(A70)                                                       
990   WRITE (6,991)                                                     
991   FORMAT(' ERROR IN PLOT ATTRIBUTES CARD ')                         
      GOTO 1010                                                         
992   WRITE (6,993)                                                     
993   FORMAT(' ERROR IN PLOT CENTER CARD ')                             
      GOTO 1010                                                         
994   WRITE (6,995)                                                     
995   FORMAT(' ERROR IN ATOMS THAT DEFINE PLANE ')                      
      GOTO 1010                                                         
996   WRITE (6,997)                                                     
997   FORMAT(' ERROR IN DUMMY ATOM INPUT CARD ')                        
      GOTO 1010                                                         
998   WRITE (6,999)                                                     
999   FORMAT(' ERROR IN FUNCTION INPUT CARD ')                          
      GOTO 1010
1100  WRITE (6,1105)
1105  FORMAT(' ERROR IN CHOICE OF ORIENTATION PROCEDURE ')
      GOTO 1010
1110  WRITE (6,1115)
1115  FORMAT(' ERROR IN EULER ANGLE ')
1010  STOP                                                              
C
C  FORMATS
  200 FORMAT(A80)                                                       
 1600 FORMAT(7X,A70)                                                    
      END